export const APP_READY = "APP_READY";

export const LOGGED_IN = "LOGGED_IN";
export const USER_PROFILE = "USER_PROFILE";
export const CREATE_CART = "CREATE_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";

export const EMPTY_USER_PROFILE = "EMPTY_USER_PROFILE";

export const HEADER_FOOTER_NEEDED_CHANGE = "HEADER_FOOTER_NEEDED_CHANGE";



export const ADDRESS_EXISTS_CHANGE = "ADDRESS_EXISTS_CHANGE";

export const CHANGE_LOADER = "CHANGE_LOADER";
export const WARNING_MESSAGE = "WARNING_MESSAGE";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";

export const SHOW_CART = 'SHOW_CART';

